payment:
  toss:
    success:
      url: "http://localhost:8080/api/v1/payments/toss/success"
    fail:
      url: "http://localhost:8080/api/v1/payments/toss/fail"
    test_client_api_key: test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq
    test_secrete_api_key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R